Repository gabealoi/TelegramBot, pull requests merged in 2024-10, with the labels that each got.

#52 Improve Media Retrieval Method in Instaloader Integration
  app/config/__init__.py
  app/config/tgram_bot_logger.py
  app/modules/__init__.py
  app/modules/instagram_content_loader.py
  app/modules/tgram_bot_helper.py
  app/tgram_bot_runner.py
  generate_session_from_cookie.py
  instagram_content_loader.py
  requirements.txt
  tgram_bot.py
Labels: enhancement

#53 Improve Authorization Handling and Add Support for Instagram Reels
  app/modules/__init__.py
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
  logs/README.md
Labels: bug, enhancement

#54 fix small import bug
  app/modules/instagram_content_loader.py
Labels: bug

#55 fix small import bug pt2
  app/modules/instagram_content_loader.py
Labels: bug

#56 reworked json data access as its different for linux request responses
  app/modules/instagram_content_loader.py
Labels: bug

#57 Improve Logging in parse_instagram_media() for Enhanced Request Failure Debugging
  app/modules/instagram_content_loader.py
Labels: bug

#58 formatted better logging; added retry counter and cookie generator on…
  app/modules/instagram_content_loader.py
Labels: bug, enhancement

#59 Enhance Session Management and Headers for Instagram API Requests
  app/modules/instagram_content_loader.py
Labels: enhancement

#60 Enhance Dockerization and Deployment
  .github/workflows/deploy.yml
  Dockerfile
Labels: enhancement

#61 updated/removed deployuser config from dockerfile
  Dockerfile
Labels: bug, enhancement

#62 updated/removed cookie save file config from dockerfile
  Dockerfile
Labels: bug, enhancement

#63 added ms driver mapped volume
  .github/workflows/deploy.yml
Labels: bug, enhancement

#64 corrected volume mappings to actual dirs, not the files
  .github/workflows/deploy.yml
Labels: bug

#65 hopefully corrected file/dir volume mounting
  .github/workflows/deploy.yml
Labels: bug

#66 added copying of deploy.sh to buildfile
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#67 deploy script set to run AFTER build completion and run
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#68 completely simplified docker buildfile; reworked github deployment
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
Labels: bug

#69 fixed execution string mismatch
  Dockerfile
Labels: bug

#70 Improvement/docker build
  Dockerfile
Labels: bug

#72 fixed missing dependency issue for msedgedriver
  Dockerfile
Labels: bug

#73 removed broken/missing depedency
  Dockerfile
Labels: bug

#74 modified deploy pipeline to account for driver mapping
  .github/workflows/deploy.yml
Labels: bug

#77 remodifying buildfile
  Dockerfile
Labels: bug

#78 added missing apt install
  Dockerfile
Labels: bug

#79 removing install to produce new image without mounts to test manual i…
  Dockerfile
Labels: bug

#80 completely fixed and modified installation of msedge and driver; ever…
  Dockerfile
Labels: bug

#82 added prompt response from installation
  Dockerfile
Labels: bug

#83 updated minor error that was causing a false 'fail' in deploy pipeline
  .github/workflows/deploy.yml
Labels: bug

#84 adding challenge handling
  app/modules/generate_cookies.py
  source_page/README.md
Labels: bug

#85 modified to file write, was read
  app/modules/generate_cookies.py
Labels: bug

#86 added basic carousel support within loader and runner
  Dockerfile
  app/modules/instagram_content_loader.py
  app/tgram_bot_runner.py
Labels: enhancement

#87 Fix/web driver
  Dockerfile
Labels: enhancement

#88 added better dockerfile loggin
  Dockerfile
Labels: enhancement

#89 remodified logging
  Dockerfile
Labels: bug

#90 remodified logging pt12
  Dockerfile
Labels: bug, enhancement

#91 fixing logging
  Dockerfile
Labels: bug, enhancement

#92 fixing logging (actually)
  Dockerfile
Labels: bug

#93 fixing logging (actually)-- quick fix
  Dockerfile
Labels: bug

#94 fixing logging (actually)-- quick fix pt 2
  Dockerfile
Labels: bug

#95 fixing logging (actually)-- quick fix pt 3--fix sytnax error
  Dockerfile
Labels: bug

#71 This adds the tiktok link feature
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
  app/modules/tgram_bot_helper.py
  app/modules/tiktok_content_loader.py
  app/tgram_bot_runner.py
  requirements.txt
Labels: enhancement

#96 commented out debug name=main line
  app/modules/tiktok_content_loader.py
  requirements.txt
Labels: bug

#97 Fix/quick fixes
  requirements.txt
Labels: bug

#98 updating config files for deployment and init for aws hosting
  .github/workflows/deploy.yml
  Dockerfile
  app/modules/__init__.py
Labels: enhancement

#99 updating config files for deployment and init for aws hosting
  .github/workflows/deploy.yml
Labels: enhancement

#100 updated user in deploy command
  .github/workflows/deploy.yml
Labels: enhancement

#101 updated ip, one step at a time :)
  .github/workflows/deploy.yml
Labels: enhancement

#103 fixed-- dont ask
  app/modules/__init__.py
Labels: bug

#104 updated cookie volume mapping + handling
  .github/workflows/deploy.yml
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
Labels: bug

#105 updated cookie handling; to be changed to read from env later
  app/modules/__init__.py
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
Labels: bug

#106 Fix tiktok links not being detected as such
  app/modules/tgram_bot_helper.py
Labels: bug

#107 Fix/quick fixes
  app/modules/__init__.py
  app/modules/generate_cookies.py
Labels: bug

#108 using environment for cookie session persistance
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
  app/modules/tiktok_content_loader.py
Labels: enhancement

#109 quick fix for return type of the session cookie fn
  app/modules/generate_cookies.py
Labels: bug

#110 even quicker fix for tiktok json serialization
  app/modules/tiktok_content_loader.py
Labels: bug

#111 made it compatible with local .env file
  app/modules/generate_cookies.py
  app/modules/instagram_content_loader.py
  app/modules/tiktok_content_loader.py
Labels: bug

#112 added .loadenv() to refresh the env variables in mem
  app/modules/generate_cookies.py
Labels: bug

#113 Improvement/env storage
  app/modules/generate_cookies.py
Labels: bug

#114 updated deploy pipeline with the removal of the vol mapping to txt file
  .github/workflows/deploy.yml
Labels: enhancement

#115 DO NOT PULL THIS INTO MAIN YET
  .github/workflows/deploy.yml
  app/modules/database/__init__.py
  app/modules/database/manager.py
  app/modules/database/metadata.py
  app/modules/instagram_content_loader.py
  app/modules/tgram_bot_helper.py
  app/modules/tiktok_content_loader.py
  app/tgram_bot_runner.py
  requirements.txt
Labels: enhancement

#116 fixed spacing issues after PR review-commit
  app/modules/database/manager.py
Labels: bug

#117 Fix/quick fixes
  requirements.txt
Labels: bug

#118 fixing basic syntax error
  .github/workflows/deploy.yml
  app/modules/database/manager.py
Labels: bug

#120 fixed post= not being assigned before db push
  app/tgram_bot_runner.py
Labels: bug

#121 posting a commit bc main out of sync for some reason
  app/tgram_bot_runner.py
Labels: bug

#122 added docker pruning/cleanup commands pre-pull of new image for bette…
  .github/workflows/deploy.yml
Labels: bug

#123 new requirements
  requirements.txt
Labels: bug

#124 Fix/quick fixes
  app/tgram_bot_runner.py
Labels: bug

#125 Fix/quick fixes
  app/tgram_bot_runner.py
Labels: bug

#126 adding refresh to bucket items and updated some old code in metadata
  app/modules/database/metadata.py
  app/tgram_bot_runner.py
Labels: bug

#127 explicitly defined autoincrement param for primary key definition
  app/modules/database/metadata.py
  app/tgram_bot_runner.py
Labels: bug

#128 added the await for async session flush
  app/tgram_bot_runner.py
Labels: bug

#129 added the await for async db transactional methods; added inbound rul…
  app/tgram_bot_runner.py
Labels: bug

#130 fixed some dir structure things for additional db transaction methods…
  app/modules/database/__init__.py
  app/modules/database/db_transactions.py
  app/tgram_bot_runner.py
Labels: bug, enhancement

#131 fixed some basic syntax error
  app/modules/database/db_transactions.py
Labels: bug

#132 bunch of fixes and new dir and db methods working
  app/modules/database/db_transactions.py
Labels: enhancement

#133 fixed the db saves of user media
  app/tgram_bot_runner.py
Labels: bug

#134 added uid col to user and link_code col to posts for querying reposts…
  app/modules/database/db_transactions.py
  app/modules/database/metadata.py
  app/modules/tgram_bot_helper.py
  app/tgram_bot_runner.py
  requirements.txt
Labels: enhancement

#135 redid table structure a little and the orm as a result
  app/modules/database/metadata.py
Labels: enhancement

#136 Feature/api
  .github/workflows/deploy.yml
  Dockerfile
  app/api/__init__.py
  app/api/models/__init__.py
  app/api/models/api_models.py
  app/api/routers/__init__.py
  app/api/routers/main.py
  app/api/routers/posts.py
  app/api/routers/users.py
  app/modules/database/__init__.py
  app/modules/database/db_transactions.py
  app/modules/database/manager.py
  app/modules/database/metadata.py
  app/tgram_bot_runner.py
  requirements.txt
Labels: enhancement

#137 tiny quick fix
  .github/workflows/deploy.yml
Labels: bug

#138 tiny quick fix pt 2
  app/modules/database/__init__.py
Labels: bug, enhancement

#139 tiny quick fix pt 3--await added
  app/tgram_bot_runner.py
Labels: bug

#140 redid media route, removed query param for get post route
  app/api/models/api_models.py
  app/api/routers/posts.py
Labels: enhancement

#141 docker deploy change with docker compose
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
Labels: bug

#142 updated path on server
  .github/workflows/deploy.yml
Labels: bug

#143 another deploy fix potentially
  .github/workflows/deploy.yml
Labels: bug

#144 another typo
  .github/workflows/deploy.yml
Labels: bug

#145 typo pt 2
  .github/workflows/deploy.yml
Labels: bug

#146 revert back to og dockerfile; figure out compose later
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#147 part two of trying to use compose
  .github/workflows/deploy.yml
Labels: bug, enhancement

#148 removed unnecessary other things
  .github/workflows/deploy.yml
Labels: bug, enhancement

#149 revert again
  .github/workflows/deploy.yml
Labels: bug

#150 redoing structure to modularize api and app logic for separate contai…
  .github/workflows/deploy.yml
  .gitignore
  api/Dockerfile.api
  api/__init__.py
  api/config/api_logger.py
  api/database/__init__.py
  api/database/manager.py
  api/database/metadata.py
  api/models/__init__.py
  api/models/api_models.py
  api/requirements.txt
  api/routers/__init__.py
  api/routers/main.py
  api/routers/posts.py
  api/routers/users.py
  app/api/routers/__init__.py
  app/api/routers/main.py
Labels: enhancement

#152 fixed typo
  .github/workflows/deploy.yml
  app/modules/database/metadata.py
  app/modules/instagram_content_loader.py
  app/modules/tgram_bot_helper.py
  app/tgram_bot_runner.py
Labels: bug, enhancement

#153 Fix/docker deploy
  .github/workflows/deploy.yml
  app/Dockerfile
  app/modules/instagram_content_loader.py
  app/requirements.txt
  app/tgram_bot_runner.py
Labels: bug, enhancement

#154 Fix/docker deploy
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  Dockerfile.api
  app/modules/database/metadata.py
  app/modules/instagram_content_loader.py
  app/modules/tgram_bot_helper.py
  app/tgram_bot_runner.py
  requirements.txt
Labels: bug, enhancement

#155 fixed docker run command
  .github/workflows/deploy.yml
Labels: bug, enhancement

#156 updated path structure within container to comply with previous struc…
  Dockerfile
  Dockerfile.api
Labels: bug

#157 uncomment s3 so it can be imported properly; syntax error
  api/database/__init__.py
Labels: bug

#158 Fix/docker deploy
  api/requirements.txt
  api/routers/main.py
  requirements.txt
Labels: enhancement

#159 Fix/docker deploy
  api/requirements.txt
  api/routers/main.py
Labels: bug
